agents:
  queue: "cardano-wallet"

env:
  LC_ALL: "C.UTF-8"
  NIX_PATH: "channel:nixos-21.11"

  # Per-host variables - shared across containers on host
  macos: "x86_64-darwin"
  linux: "x86_64-linux"
  nix: "nix develop --accept-flake-config --allow-import-from-derivation"

steps:

  - label: 'Check nix develop (linux)'
    key: linux-nix
    commands: |
      ${nix} --command bash -c "echo +++ nix develop"
    agents:
      system: ${linux}
    env:
      TMPDIR: "/tmp"

  - label: "Build .agda .hs"
    depends_on: linux-nix
    command: |
      ${nix} --command bash -c 'just ci-build'
    agents:
      system: ${linux}
    env:
      TMPDIR: "/tmp"
  
  - label: "Check unit tests"
    depends_on: linux-nix
    command: |
      ${nix} --command bash -c 'just ci-check'
    agents:
      system: ${linux}
    env:
      TMPDIR: "/tmp"
      
  - block: Cabal Build
    if: |
      build.branch !~ /^gh-readonly-queue\/master/
          && build.branch != "master"
    depends_on:
      - linux-nix
    key: cabal-release-block

  - label: Cabal Build (linux)
    key: cabal-release
    depends_on: cabal-release-block
    command: |
      ${nix} -c cabal update
      ${nix} -c cabal build all -frelease
    agents:
      system: ${linux}
