agents:
  queue: "cardano-wallet"

env:
  LC_ALL: "C.UTF-8"
  NIX_PATH: "channel:nixos-21.11"

  # Per-host variables - shared across containers on host
  macos: "x86_64-darwin"
  linux: "x86_64-linux"
  nix: "nix develop --accept-flake-config --allow-import-from-derivation"

steps:

  - label: 'Check nix develop (linux)'
    key: linux-nix
    commands: |
      ${nix} --command bash -c "echo +++ nix develop"
    agents:
      system: ${linux}
    env:
      TMPDIR: "/tmp"

  - group: "Build artifacts"
    depends_on: linux-nix
    steps:

    - label: "Build .agda"
      key: build-agda
      depends_on: []
      command: |
        ${nix} --command bash -c 'just ci-build-agda'
      agents:
        system: ${linux}
      env:
        TMPDIR: "/tmp"

    - label: "Build .hs"
      key: build-hs
      depends_on: []
      command: |
        ${nix} --command bash -c 'just ci-build-hs'
      agents:
        system: ${linux}
      env:
        TMPDIR: "/tmp"

  - label: "Check unit tests"
    depends_on: linux-nix
    command: |
      ${nix} --command bash -c 'just ci-check'
    agents:
      system: ${linux}
    env:
      TMPDIR: "/tmp"

  - group: Code quality
    depends_on: linux-nix
    steps:

    - label: Check Code Format
      key: code-format
      depends_on: []
      command: |
        ${nix} --command scripts/buildkite/main/check-code-format.sh
      agents:
        system: ${linux}

    - label: Check HLint
      key: hlint
      depends_on: []
      command:
        ${nix} --command bash -c "echo +++ HLint ; hlint lib/cardano-wallet-read"
      agents:
        system: ${linux}

    - label: Check HLS Works
      key: hls
      depends_on: []
      command:
          ${nix} --command bash -c "haskell-language-server lib/cardano-wallet-read/haskell/Cardano/Wallet/Read.hs"
      agents:
        system: ${linux}
      env:
        TMPDIR: "/cache"